### ISSUE TITLE
can't work on GPU?

### ISSUE THREAD

**Issue by libonwpu** [fkodom/fft-conv-pytorch#1]
Dear authors,

I am interested in this work and thanks for your share. I find this function can't work on GPU. Is it true?

**Comment by fkodom** [comment]
You're exactly right, that was a bug on my part. I just pushed a fix for this. Thank you for pointing this out!  I missed this when updating for PyTorch 1.7.

However, FFT convolution is usually slower than direct convolution on the GPU.  Direct conv is just so fast on GPU, you'd need **really, really** kernel sizes before FFT conv was faster.  If you need GPU execution, you're almost certainly better off using direct convolution.
