### ISSUE TITLE
Stride

### ISSUE THREAD

**Issue by fshamsafar** [fkodom/fft-conv-pytorch#2]
Thank you for this code. How can I specify the stride just like a normal conv layer? Thanks.

**Comment by fkodom** [comment]
Stride isn't implemented right now, but would be fairly easy to add.  You just have to compute strides after performing the inverse FFT. (Can't do striding in Fourier space.)

I'll try to get this in soon.  Will update here once that happens.

**Comment by fkodom** [comment]
Just added this feature.  You can now specify `stride` just like in a normal conv layer.  Ex:
```
conv_layer = FFTConv1d(16, 32, 3, stride=2)
```

**Note:**  You won't see any speed-ups from using `stride > 1` with Fourier convolutions.  We can't compute the striding in Fourier space, so it's just applied at the end, after computing the inverse Fourier transform.  Runtime should be almost identical for different `stride` values.
