### ISSUE TITLE
Propagation of error becomes large very fast

### ISSUE THREAD

**Issue by dwromero** [fkodom/fft-conv-pytorch#4]
Hi fkodom,
I was trying to experiment with your fftconv implementation but I saw that just after 2 layers the error becomes quite large. Is it due to a malinterpretation of your code from my part? Might it be that the FFT + IFFT simply introduce too much error when concatenated?

Thank you in advance for your help! :) 
David

![image](https://user-images.githubusercontent.com/38861840/102353610-995d8d00-3fa9-11eb-8bb0-b578724d7581.png)

**SOLUTION:**
The problem is that the convolution was growing very largely, for which a difference of 1e-3 was not that big. In short the method works fantastically good :)

**Comment by fkodom** [comment]
Sorry for the delay here -- was away from work for a few days.  Glad you figured it out!
